### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Eric1212** [monosoul/git-extended-update-index-plugin#59]
I'm alone with that error ?
--- System Info ---
IntelliJ IDEA 2024.2.2 (Community Edition)
Build #IC-242.22855.74, built on September 18, 2024
Runtime version: 21.0.3+13-b509.15 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10
---

com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.github.monosoul.git.updateindex.extended.MakeNotExecutableAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: git-extended-update-index]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

@monosoul if you see this, thanks in advance !

**Comment by Iworb** [comment]
You're not alone. Same issue here

**Comment by monosoul** [comment]
I'll have a look

**Comment by Eric1212** [comment]
> I'll have a look

You're a charm.
